version: '3.7'
services:

  traefik:
    # Use the latest Traefik image
    image: traefik:v2.4

  php:
    image: serversideup/php:8.2-fpm-nginx
    working_dir: /var/www/html

  # meilisearch:
  #   image: getmeili/meilisearch:v0.27.2
  #   depends_on:
  #     - "redis"
  #   environment:
  #     MEILI_NO_ANALYTICS: "true"

  mysql:
    image: mysql:8
  
  node:
    image: node:lts
  
  redis:
    image: redis:6